### ISSUE TITLE
CC for low energy neutrino

### ISSUE THREAD

**Issue by TomaszGolan** [NuWro/nuwro#9]
Prevent running CC with neutrino energy lower than the mass of a corresponding lepton.

**Comment by cjusz** [comment]
There is no point in preventing this. 
If the cross section is zero there is no attempt to generate real events for this channel. 
On the other hand if the difference is very small the interaction may still happen, 
due to Fermi motion energy or correlated pairs energy of the neutron.

**Comment by TomaszGolan** [comment]
Although, if you run only CC QEL you may end with segmantaion fault (e.g. muon neutrino, E < 105 MeV).

**Comment by cjusz** [comment]
Solved. I made small change which prevents nuwro from trying to generate real events if all enabled channels cross sections are zero.
